/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface IAddProduct {
  /**
   * @example 50
   */
  dicount: number;
  /**
   * @example http//laptop.png
   */
  image?: string;
  /**
   * @example Laptop
   */
  name: string;
  /**
   * @example 145
   */
  price: number;
  /**
   * @example 166
   */
  sku: number;
}

export interface IProduct {
  /**
   * @example 50
   */
  dicount: number;
  /**
   * @example 63f9ba82a4f3093d9b4a5c0e
   */
  id: string;
  /**
   * @example http//laptop.png
   */
  image?: string;
  /**
   * @example Laptop
   */
  name: string;
  /**
   * @example 145
   */
  price: number;
  /**
   * @example 166
   */
  sku: number;
}
